spring:
  jpa:
  properties:
  hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  ddl-auto: update
  # MySql
  datasource:
    url: jdbc:postgresql://localhost:5432/wagginton_db_dev
    username: postgres
    password: 123456
    # Connection Pool
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
